// Generated by https://quicktype.io

export interface Item {
	Stock: number;
	Length: number;
	Tags: string[];
	Description: string;
	SalePrice: number;
	Title: string;
	SKU: string;
	Price: number;
	ImgURL: string;
	OnSale: boolean;
	ID: string;
	Width: number;
	Height: number;
	Weight: number;
	Categories: string[];
  Img: string;
}
